#!/bin/sh
set -eu

project_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
config_file="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/input.lua"
managed_file="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hypr_control.lua"
state_file="${XDG_CONFIG_HOME:-$HOME/.config}/hypr-control/settings.json"
launcher_dir="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
bin_dir="$HOME/.local/bin"
plugin_dir="${XDG_CONFIG_HOME:-$HOME/.config}/omarchy/plugins/mac.hypr-control"

mkdir -p "$launcher_dir" "$bin_dir" "$(dirname "$managed_file")" "$(dirname "$state_file")" "$(dirname "$plugin_dir")"
ln -sfn "$project_dir/bin/hypr-control-cli" "$bin_dir/hypr-control-cli"
ln -sfn "$project_dir/bin/hypr-control" "$bin_dir/hypr-control"
ln -sfn "$project_dir/hypr-control.desktop" "$launcher_dir/hypr-control.desktop"
ln -sfn /usr/share/omarchy/shell/Ui "$project_dir/standalone/Ui"
ln -sfn /usr/share/omarchy/shell/Commons "$project_dir/standalone/Commons"
python "$project_dir/tools/sync_omarchy_panels.py"
rm -f "$plugin_dir"

if [ ! -e "$managed_file" ]; then
  printf '%s\n' '-- Generated by Hypr Control. Edit settings through the app.' > "$managed_file"
fi

if [ ! -e "$state_file" ]; then
  printf '%s\n' '{"devices": {}, "version": 1}' > "$state_file"
fi

backup_file=
if ! grep -Fq 'require("hypr.hypr_control")' "$config_file"; then
  backup_file="$config_file.hypr-control-backup.$(date +%s)"
  cp "$config_file" "$backup_file"
  printf '\n-- Settings managed by Hypr Control.\nrequire("hypr.hypr_control")\n' >> "$config_file"
fi

hyprctl reload >/dev/null
errors=$(hyprctl configerrors)
if [ -n "$errors" ]; then
  if [ -n "$backup_file" ]; then
    cp "$backup_file" "$config_file"
    hyprctl reload >/dev/null
  fi
  printf '%s\n' "$errors" >&2
  exit 1
fi

omarchy-shell shell rescanPlugins >/dev/null
printf 'System Settings installed as a standalone Quickshell application.\n'
